cars = ["BMW","Nexia", "Mers", "Xammer","lasetti"]
# print(cars)
# print(cars[0])
# print(cars[1])
# print(cars[2])
# print(cars[3])
# print(cars[4])
# cars[0] = "Bugate"
# cars[1] ="limuzin"
# cars[2] = "lanbarjini"
# cars[3] ="lada"
# cars[4] = "Ferari"
# print(cars)
# num1 = [1,2,3,4,5,6,7,8,9,10]
# num2 = [11,12,13,14,15,16,17,18,19,20]
# # print(num1[0]+num2[0])
# # print(num1[1]+num2[1])
# # print(num1[2]+num2[2])
# # print(num1[3]+num2[3])
# # print(num1[4]+num2[4])
# # print(num1[5]+num2[5])
# # print(num1[6]+num2[6])
# # print(num1[7]+num2[7])
# # print(num1[8]+num2[8])
# # print(num1[9]+num2[9])
# print(num1[0]+num1[1]+num1[2]+num1[3]+num1[4]+num1[5]+num1[6]+num1[7]+num1[8]+num1[9])
# ismlar=[]
# ismlar.append('Aziz')
# ismlar.append('Zafar')
# print(ismlar)
# ismlar.remove('Aziz')
# print(isimlar )
# isimlar=["Alisher","Murod","Alirizo"]
# print("salom",isimlar[0],"Bugun choyhona bormi")
# print("Salom",isimlar[1],"Bugun maktabga bordingmi")
# print("Qondaysan",isimlar[2],"Bugun kampitur honaga boramizmi")
# names=['Zafar','aziz','aziza','dilshod']
# number=[1,2,3,4,5,6,7,8,9]
# Ist=["Aziz","Zafar",1,[4,5]]
# Ist=[[1,2,3],[4,5,6],[7,8,9]]
# print(Ist[0][0])
# print(Ist[0][1])
# print(Ist[0][2])
# print(Ist[1][0])
# print(Ist[1][1])
# print(Ist[1][2])
# print(Ist[2][0])
# print(Ist[2][1])
# print(Ist[2][2])
# ks=[-1,-2,-3,-4,-5,-6,-67,-8,-9]
# # max_num= max(ks)
# # min_num=min(ks)
# uzunlik=len(ks)
# print(uzunlik)
# print(max_num+min_num)
# groceryList = ["Rice","Wheat","Barley"]
# print(groceryList)
# myNumbers = [1,5,9,16,28]
# print(myNumbers)
# myNumbers = [1,5,5,9,9,9,16,28]
# print(myNumbers)
# heterogeneousList = ["Python",123,24.5,True,35,"a"]
# print(heterogeneousList)
# ProgrammingList = ["CSharp","Python","PHP","R"]
# print(len(ProgrammingList))
# fruits = ["apple","banana","mango"]
# bananaIndex = fruits.index("banana")
# mangoIndex = fruits.index("mango")
# print(bananaIndex)
# print(mangoIndex)

# pythonList = ["p","y","t","h","o","n"]

# # to get the 1st item
# print(pythonList[0])

# #to get the 4th item
# print(pythonList[3])

# # Negative indexing to get last item
# print(pythonList[-1])

# # To get second last item
# # print(pythonList[-2])
# myList = ['p','y','t','h','o','n','i','s','t','a']

# # elements from 5 to 8
# print(myList[4:8])

# # from 1st element to 4th element
# print(myList[:4])

# # from 8th element to last element 
# print(myList[7:])

# # from 1st to last elements
# print(myList[:])

# # negative slicing
# print(myList[-1:-9])

# print(myList[-5:])

# print(myList[:-4])
# numbers = [10,20,30,40,50,60]

# numbers.append(70)
# print(numbers)
# numbers=[10,20,30,40,50,60]
# numbers.append(80)
# print(numbers)
# numbers = [10,20,30,40,50,60]

# numbers.insert(4,600)
# print(numbers)
# list1 = ["Apple","Orange","Mango"]
# list2 = ["Grape","Strawberry"]

# list1.extend(list2)
# print(list1)
# x = [23,45,67,89,34,12]

# # removing the last element
# x.pop()
# print(x)

# # removing the 0th index element
# x.pop(0)
# print(x)

# dryFruits = ["Cashew nuts","Dates","Almonds","Raisins"]

# dryFruits.remove("Cashew nuts")
# print(dryFruits)

# dryFruits = ["Cashew nuts","Dates","Almonds","Raisins"]

# dryFruits.clear()
# print(dryFruits)
# dryFruits = ["Cashew nuts","Dates","Almonds","Raisins"]

# d = dryFruits.copy()
# print(d)
# myList = [1,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4]

# count = myList.count(2)
# print(count)
# myList = ["Pen","Pencil","Book"]

# myList.reverse()
# print(myList)
# myList = ["Pen","Pencil","Book","Eraser"]
# numbers=[2,4,6,8,1,3,5,9]
# numbers.sort()
# myList.sort()
# print(myList)
# print(numbers)
# colorList = ["Red","Blue","Green","Yellow","Orange","Purple"]

# # deleting an item
# del colorList[2]
# print(colorList)

# # # deleting multiple items
# del colorList[1:3]
# print(colorList)

# # # deleting the entire list
# del colorList
# nestedList = ["Apple",["Ball",1,2.5],['a',128]]

# print(nestedList)
# print(nestedList[0])
# print(nestedList[1])
# print(nestedList[2])
# myList1 = ["Mac","Windows","Linux"]
# myList2 = ["Book","Pencil","Pen"]

# combinedList = myList1 + myList2

# print(combinedList)
# myList1 = ["Mac","Windows"]

# combinedList = myList1 * 3
# print(combinedList)
# myList = [2**x for x in range(10)]
# print(myList)
# 2024
# student = {
#     'ism':'alisher',
#     'Familya': 'Obitov',
#     'yosh':19,
#     'kurs':1

#     }
# print(student)
# print(student['ism'])
# print(student['Familya'])
# print(student['yosh'])
# print(student['kurs'])
# 2025
# print(student['ism'])
# student['ism'] = 'abubakr'
# student['Familya'] = 'abubakrova'
# student['yosh'] = '20'
# student['kurs'] = '2'
# print(student)
# user = {
#     'ism':'Aziz',
#     'familya':'zafarov',
#     'Sinf':10,
#     'fanlar'   : ['ingliz tili','rus tili','tarix','algebra']
# }
# print(user['fanlar'][0])
# print(user['fanlar'][1])
# print(user['fanlar'][2])
# print(user['fanlar'][3])

# user['baho']=[1,2,3,4,5]
# user ['otasining_ismi'] = "Sultonbek o'g'li"
# print(user)

# recept_osh = {
#     1:"sabzi",
#     2:"gusht",
#     3:"yog'"
# }
# print (recept_osh[1])

# child = {
# 'name' :"sarvar",
# 'familya':"samirov",
# 'fathir':{
#     'name': "Aslam",
#     "familya":"samirov"
# },
# 'mothir':{
#     'name':"Aziza",
#     'familya':"samirova"
# }
# }
# print (child)
# print (child['familya']['name'])


print('Assalom alaykum')
# a = "hello world"
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# print(a)
# a =  list(range(1,20))
# print(a)
# for i in range(10):
#     print(i,"hello world")
# d = [1,2,3,4,5,6,7,8,9,0]
# print(ls[0])
# print(ls[1])
# print(ls[2])
# print(ls[3])
# print(ls[4])
# print(ls[5])
# print(ls[6])
# print(ls[7])
# print(ls[8])
# print(ls[9])
# ismlar = ["aziz","xasan","javlon","javohir","kamol"]
# for a in ismlar:
#     print(a)
# numbers = [10,2,3,1,4,5,6,7,8,9]
# print(numbers[0]+numbers[1]+numbers[2]+numbers[3]+numbers[4]+numbers[5]+numbers[6]+numbers[7]+numbers[8]+numbers[9])
# m = 0
# for a in numbers:
#     m+=a
#     print(m)
# m = 1
# for a in numbers:
#     m*=a
#     print(m)
# 
# text = "hello world"
# for a in text:
#     print(a)
# print('Assalom alaykum')
# print("Hayrli tong!")
# print(2+4*2)
# print(19/5)
# print(2**4)
# print("nexia","tico","damas","korganlar qilar havas")
# print(5**4)
# print(22/4)
# print(125*125)
# print(2*(125+125))
# word = "hello world"
# print(word)
# xabar = "salom"
# xabar = "yaxshi"
# print(xabar)
# class = "hello"
# print(class)
# radius = 5
# pi = 3.14159
# aylana_yuzi = pi * radius**2
# print("Radiusi" , radius, "ga teng aylananing yuzi=", aylana_yuzi)
# kocha = "bogbon"
# mahalla = "sogbon"
# tuman = "bodomzor"
# viloyat = "samarqand"
# print(kocha + "" "kochasi", mahalla + "" "mahallasi", tuman + "" "tumani", viloyat + "" "viloyati")
# manzil = (f"{kocha} kochasi, {mahalla} mahallasi, {tuman} tumani, {viloyat} viloyati")
# print(manzil)
# print(manzil.upper())
# print(manzil.lower())
# print(manzil.capitalize())
# print(manzil.title())
# ismlar = ["raxmon", "xasan" ,"asilbek"]
# print("salom" + ismlar[0] + "ishlaring yxshimi")
# print(ismlar[1] +"bugun futbolga boramizmi")
# print(ismlar[2] + "ertaga maktabga borasanmi")